f -- MySQL Script generated by MySQL Workbench
-- Thu Jul  9 09:51:45 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS,
  UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS,
  FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE,
  SQL_MODE = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb`;
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8;
USE `mydb`;
-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_nascimento` DATE NOT NULL,
  `num_cc` VARCHAR(9) NOT NULL,
  `nif` VARCHAR(9) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `apelido` VARCHAR(100) NOT NULL,
  `morada` VARCHAR(150) NOT NULL,
  `codigo_postal` VARCHAR(7) NOT NULL,
  `telefone` VARCHAR(9) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `criado_em` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `tipo` ENUM('admin', 'candidato') NOT NULL DEFAULT 'candidato',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `num_cc_UNIQUE` (`num_cc` ASC) VISIBLE,
  UNIQUE INDEX `nif_UNIQUE` (`nif` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `mydb`.`candidato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`candidato` (
  `user_id` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `instituicao_1` VARCHAR(45) NOT NULL,
  `instituicao_2` VARCHAR(45) NULL,
  `instituicao_3` VARCHAR(45) NULL,
  `curso` VARCHAR(100) NOT NULL,
  `ano_letivo` VARCHAR(20) NOT NULL,
  INDEX `fk_candidato_user1_idx` (`user_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_candidato_user1` FOREIGN KEY (`user_id`) REFERENCES `mydb`.`user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `user_id` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(45) NOT NULL,
  `nif` VARCHAR(9) NOT NULL,
  `telefone` VARCHAR(12) NOT NULL,
  INDEX `fk_admin_user_idx` (`user_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_admin_user` FOREIGN KEY (`user_id`) REFERENCES `mydb`.`user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `mydb`.`agregado_familiar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`agregado_familiar` (
  `candidato_id` INT NOT NULL,
  `íd` INT NOT NULL AUTO_INCREMENT,
  `nif` VARCHAR(9) NOT NULL,
  `nome_completo` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(9) NOT NULL,
  INDEX `fk_table1_candidato1_idx` (`candidato_id` ASC) VISIBLE,
  PRIMARY KEY (`íd`),
  UNIQUE INDEX `nif_UNIQUE` (`nif` ASC) VISIBLE,
  CONSTRAINT `fk_table1_candidato1` FOREIGN KEY (`candidato_id`) REFERENCES `mydb`.`candidato` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `mydb`.`documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`documentos` (
  `candidato_id` INT NOT NULL,
  `tipo_documento` ENUM(
    'Formulario_candidatura',
    'CC',
    'Declaracao_Residencia',
    'Declaracao_Domicilio_Fiscal',
    'Comprovativo_Inscricao_Matricula',
    'Documento_bolsa_estudo',
    'IRS',
    'Comprovativos_Rendimento_Anuais'
  ) NOT NULL,
  `url_ficheiro` VARCHAR(255) NOT NULL,
  `criado_em` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `estado` ENUM('pendente', 'aprovado', 'rejeitado') NOT NULL DEFAULT 'pendente',
  INDEX `fk_table2_candidato1_idx` (`candidato_id` ASC) VISIBLE,
  CONSTRAINT `fk_table2_candidato1` FOREIGN KEY (`candidato_id`) REFERENCES `mydb`.`candidato` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;